### ISSUE TITLE
Build time test failure on 32bit architectures

### ISSUE THREAD

**Issue by tillea** [svi-opensource/libics#6]
Hi,
I have upgraded the Debian package of libics to version 1.6.1.  Unfortunately on 32bit architectures the test suite uncovers an error as you can read in the according [bug report](https://bugs.debian.org/882430).
Kind regards, Andreas.

**Comment by ghost** [comment]
This turned out to be a bug in the test program. It has been fixed, and an new version released (1.6.2)

thanks for the report!
